#!/bin/bash
printf "\033[1;33m    _\n __(.)<\033[1;34m Ducks (du -cks)\n\033[1;33m \___) \033[1;34m Find the large files.\n\n"; printf "\033[4;36mWorking dir: "; pwd; printf "\033[0m\n"; printf " Size    Name\n\n"
sp()
{
    local pid=$!
    local dy=0
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $dy
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}
du -cks * | sort -rn | head & sp
